### ISSUE TITLE
matching roles from ldap not working

### ISSUE THREAD

**Issue by Miaouw17** [antonio-castellon/module-ldap#1]
There's a little bug on ldap.js line 86 on getRoles function that prevent proper working.
It should be ".includes" instead of ".indexOf" (or maybe contains) here : 

listOfRoles.forEach(function(value){
            if (_group.**indexOf**( setup.ROLES[value] ) > 0) {   ==> if (_group.**includes**( setup.ROLES[value] ) > 0) {
              roles['is' + value] = true;
            }
});

**Comment by antonio-castellon** [comment]
well... it depends on how you declare the LDAP group (I avoid the starting definition tht always was the same for all roles), but you're right it will be better to use includes that takes as well all the defined code. Many thanks.

**Comment by antonio-castellon** [comment]
new version 1.06 is available ;)

**Comment by Miaouw17** [comment]
Many thanks !
